name: CI Pipeline

on:
  push:
    branches:
      - dev
      - 'release/*'
    tags:
      - 'v*'

env:
  PROJ: ${{ vars.PROJ }}
  APP: cdn
  ENV: ${{ vars.ENV }}
  REGISTRY: ${{ vars.REGISTRY }}
  REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE: $PROJ-$APP

jobs:
  download:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  configure:
    needs: download
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
                    startsWith(github.ref, 'refs/heads/release') && 'qa' ||
                    startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=$IMAGE
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  build-and-push:
    needs: configure
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
                    startsWith(github.ref, 'refs/heads/release') && 'qa' ||
                    startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-contexts: app=.
          push: true
          tags: ${{ needs.configure.outputs.tags }}
          labels: ${{ needs.configure.outputs.labels }}
          target: $ENV
